### ISSUE TITLE
Apply REFoCUS to the walking-aperture dataset which is received by a part of the transducer elements

### ISSUE THREAD

**Issue by Yuxin-Zhang-Jasmine** [nbottenus/REFoCUS#2]
I created a Field II simulated walking-aperture dataset in which the elements for Tx equals to the elements for Rx for each beamline.  
And I applied the code of REFoCUS to that with Tikhonov. 

I understand that in this case the recovering of the complete dataset would be hard, but I feel strange about that the beamformed image of the 'recovered complete set' is worse than that of the 'original walking aperture data'

**Comment by rehmanali1994** [comment]
The REFoCUS technique in that paper relies on the assumption that you are capturing received channel data on the same receive channels for each transmit beam. The first way to overcome this is to apply REFoCUS across the transmit events that contribute to each receive channel. So basically, you will have to apply REFoCUS to each receive channel individually. Each receive channel will have a different set of contributing transmit beams. The only issue with this is that you will have very poor recovery of the receive channel data corresponding to the edge-most transmit elements. The second way to overcome this issue is use an iterative framework to recover channel data that is more robust to this ill-conditioned problem. You might want to see this conference proceedings paper (Iterative Retrospective Recovery of Full Synthetic Aperture Data from Focused Transmissions) as well. I hope that helps.
